#Begin: Configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-deployment-init-configmap
data:
  mysql-init.sql: |
    CREATE TABLE `election_app`.`election_results` (
    `election_uuid` CHAR(36) NOT NULL,
    `party_id` INT UNSIGNED NOT NULL,
    `number_of_votes` INT UNSIGNED NOT NULL,
    UNIQUE INDEX `primary_index` (`election_uuid` ASC, `party_id` ASC));

    CREATE TABLE `election_app`.`parties` (
    `party_id` INT UNSIGNED NOT NULL,
    `party_name` VARCHAR(50) NOT NULL,
    `party_description` VARCHAR(180),
    PRIMARY KEY(`party_id`));

    CREATE TABLE `election_app`.`elections` (
    `election_uuid` CHAR(36) NOT NULL,
    `election_name` VARCHAR(50) NOT NULL,
    PRIMARY KEY(`election_uuid`));

    INSERT INTO parties (party_id, party_name, party_description) VALUES (0, 'Andere', 'Alle nicht aufgefuehrten Parteien');
    INSERT INTO parties (party_id, party_name, party_description) VALUES (1, 'CDU', 'Christlich Demokratische Union Deutschlands');
    INSERT INTO parties (party_id, party_name, party_description) VALUES (2, 'SPD', 'Sozialdemokratische Partei Deutschlands');
    INSERT INTO parties (party_id, party_name, party_description) VALUES (3, 'Gruene', 'BUENDNIS 90/DIE GRUENEN');
    INSERT INTO parties (party_id, party_name, party_description) VALUES (4, 'FDP', 'Freie Demokratische Partei');
    INSERT INTO parties (party_id, party_name, party_description) VALUES (5, 'AFD', 'Alternative für Deutschland');
    INSERT INTO parties (party_id, party_name, party_description) VALUES (6, 'CSU', 'Christlich-Soziale Union in Bayern e.V.');
    INSERT INTO parties (party_id, party_name, party_description) VALUES (7, 'Linke', 'DIE LINKE');

    INSERT INTO elections (election_uuid, election_name) VALUES ('fdf293ee-bace-40c9-845d-1fb559b50e72', 'Bad Mergentheim');
    INSERT INTO elections (election_uuid, election_name) VALUES ('1df293ee-bace-40c9-845d-1fb559b50e72', 'Plankstadt');
    INSERT INTO elections (election_uuid, election_name) VALUES ('2df293ee-bace-40c9-845d-1fb559b50e72', 'Ludwigsburg');

    INSERT INTO election_results (election_uuid, party_id, number_of_votes) VALUES ('fdf293ee-bace-40c9-845d-1fb559b50e72', 1, 200);
    INSERT INTO election_results (election_uuid, party_id, number_of_votes) VALUES ('fdf293ee-bace-40c9-845d-1fb559b50e72', 2, 300);
    INSERT INTO election_results (election_uuid, party_id, number_of_votes) VALUES ('fdf293ee-bace-40c9-845d-1fb559b50e72', 3, 150);
    INSERT INTO election_results (election_uuid, party_id, number_of_votes) VALUES ('fdf293ee-bace-40c9-845d-1fb559b50e72', 4, 100);
    INSERT INTO election_results (election_uuid, party_id, number_of_votes) VALUES ('fdf293ee-bace-40c9-845d-1fb559b50e72', 5, 120);
    INSERT INTO election_results (election_uuid, party_id, number_of_votes) VALUES ('fdf293ee-bace-40c9-845d-1fb559b50e72', 6, 60);
    INSERT INTO election_results (election_uuid, party_id, number_of_votes) VALUES ('fdf293ee-bace-40c9-845d-1fb559b50e72', 7, 70);
    INSERT INTO election_results (election_uuid, party_id, number_of_votes) VALUES ('fdf293ee-bace-40c9-845d-1fb559b50e72', 0, 50);

    INSERT INTO election_results (election_uuid, party_id, number_of_votes) VALUES ('1df293ee-bace-40c9-845d-1fb559b50e72', 1, 100);
    INSERT INTO election_results (election_uuid, party_id, number_of_votes) VALUES ('1df293ee-bace-40c9-845d-1fb559b50e72', 2, 350);
    INSERT INTO election_results (election_uuid, party_id, number_of_votes) VALUES ('1df293ee-bace-40c9-845d-1fb559b50e72', 3, 250);
    INSERT INTO election_results (election_uuid, party_id, number_of_votes) VALUES ('1df293ee-bace-40c9-845d-1fb559b50e72', 4, 300);
    INSERT INTO election_results (election_uuid, party_id, number_of_votes) VALUES ('1df293ee-bace-40c9-845d-1fb559b50e72', 5, 520);
    INSERT INTO election_results (election_uuid, party_id, number_of_votes) VALUES ('1df293ee-bace-40c9-845d-1fb559b50e72', 6, 300);
    INSERT INTO election_results (election_uuid, party_id, number_of_votes) VALUES ('1df293ee-bace-40c9-845d-1fb559b50e72', 7, 150);
    INSERT INTO election_results (election_uuid, party_id, number_of_votes) VALUES ('1df293ee-bace-40c9-845d-1fb559b50e72', 0, 80);

    INSERT INTO election_results (election_uuid, party_id, number_of_votes) VALUES ('2df293ee-bace-40c9-845d-1fb559b50e72', 1, 600);
    INSERT INTO election_results (election_uuid, party_id, number_of_votes) VALUES ('2df293ee-bace-40c9-845d-1fb559b50e72', 2, 500);
    INSERT INTO election_results (election_uuid, party_id, number_of_votes) VALUES ('2df293ee-bace-40c9-845d-1fb559b50e72', 3, 450);
    INSERT INTO election_results (election_uuid, party_id, number_of_votes) VALUES ('2df293ee-bace-40c9-845d-1fb559b50e72', 4, 200);
    INSERT INTO election_results (election_uuid, party_id, number_of_votes) VALUES ('2df293ee-bace-40c9-845d-1fb559b50e72', 5, 20);
    INSERT INTO election_results (election_uuid, party_id, number_of_votes) VALUES ('2df293ee-bace-40c9-845d-1fb559b50e72', 6, 40);
    INSERT INTO election_results (election_uuid, party_id, number_of_votes) VALUES ('2df293ee-bace-40c9-845d-1fb559b50e72', 7, 80);
    INSERT INTO election_results (election_uuid, party_id, number_of_votes) VALUES ('2df293ee-bace-40c9-845d-1fb559b50e72', 0, 50);

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: my-mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-mysql
  template:
    metadata:
      labels:
        app: my-mysql
    spec:
      # Mount the configmap volume
      # This is an excerpt of deployment.spec.template.spec
      volumes:
        - name: init-volume
          configMap:
            name: mysql-deployment-init-configmap
      containers:
        - name: my-mysql
          image: mysql
          volumeMounts:
            - name: init-volume
              mountPath: /docker-entrypoint-initdb.d/
          # Set required environment variables to initialize the container
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "mysecretpw"
            - name: MYSQL_DATABASE
              value: "election_app"
          ports:
            - containerPort: 33060

---
#Begin: Service
apiVersion: v1
kind: Service
metadata:
  name: my-app-mysql-service
spec:
  selector:
    app: my-mysql
  ports:
    - name: mysql-xproto
      protocol: TCP
      port: 33060
      targetPort: 33060
#End: Service
